<?php

namespace App\Services\Detection;

use Transliterator;

/**
 * Deterministic normalization, applied before blocking and before scoring.
 *
 * Everything here is a pure string function — no database, no Eloquent. The
 * seeder writes these keys onto every row; `detect:run` rewrites them; the
 * blocking self-joins then compare already-normalized text.
 *
 * Accent folding happens **here, in PHP**, not in SQL. Postgres' `unaccent`
 * extension is enabled, but the blocking queries never call it: a key is
 * unaccented before it is stored, so `a.name_key % b.name_key` compares two
 * ASCII strings. Keeping the fold on this side is what lets the whole class be
 * unit-tested without a database.
 */
class Normalizer
{
    private static ?Transliterator $transliterator = null;

    /**
     * The `contacts.name_key` blocking key: the full name, normalized.
     *
     * Nicknames are **not** expanded here. `jen smith` and `jennifer smith` stay
     * distinct keys, and trigram similarity between them (~0.3) sits right at the
     * threshold — which is why the hero pair is generated by the household block,
     * not this one. Expansion happens at scoring, from `config/nicknames.php`.
     */
    public function nameKey(?string $firstName, ?string $lastName): ?string
    {
        return $this->blankToNull($this->name(trim(($firstName ?? '').' '.($lastName ?? ''))));
    }

    /**
     * Lowercase, unaccent, strip non-alpha, collapse whitespace.
     *
     * Non-alpha characters are dropped rather than replaced with a space, so
     * `Smith-Jones` folds to one token (`smithjones`) instead of two. Whitespace
     * itself is preserved through the strip and collapsed afterwards — otherwise a
     * tab between names would fuse them into a single word.
     */
    public function name(?string $value): string
    {
        $value = $this->fold($value);
        $value = preg_replace('/[^a-z\s]/', '', $value) ?? '';

        return $this->collapse($value);
    }

    /**
     * Lowercase + trim. Plus-addressing and gmail-dot canonicalization are
     * deliberately not folded — they'd merge addresses that deliver to one inbox
     * but were entered as distinct identities, which is a scoring judgment rather
     * than a normalization one.
     */
    public function email(?string $value): ?string
    {
        return $this->blankToNull(mb_strtolower(trim($value ?? '')));
    }

    /**
     * Strip to digits and compare on the last 10 (US). E.164 is the production
     * form; this is the weekend equivalent that survives `+1`, dashes, and parens.
     */
    public function phone(?string $value): ?string
    {
        $digits = preg_replace('/\D/', '', $value ?? '') ?? '';

        return $this->blankToNull(
            mb_strlen($digits) > 10 ? mb_substr($digits, -10) : $digits,
        );
    }

    /**
     * The `contacts.address_key` blocking key, built from the contact's primary
     * address: `address_1 + city + zipcode`, normalized. `address_2` is excluded
     * — a unit number is what *distinguishes* two households at one street
     * address, so folding it in would pull neighbors together.
     */
    public function addressKey(?string $address1, ?string $city, ?string $zipcode): ?string
    {
        $parts = array_filter([$address1, $city, $zipcode], fn (?string $part) => $this->blankToNull($part ?? '') !== null);

        return $this->blankToNull($this->address(implode(' ', $parts)));
    }

    /**
     * Lowercase, unaccent, strip punctuation, collapse whitespace. Digits survive
     * — a street number and a zip are most of the signal.
     */
    public function address(?string $value): string
    {
        $value = $this->fold($value);
        $value = preg_replace('/[^a-z0-9]+/', ' ', $value) ?? '';

        return $this->collapse($value);
    }

    /**
     * Lowercase and strip accents: `José` → `jose`, `Ædán` → `aedan`.
     */
    private function fold(?string $value): string
    {
        $value = mb_strtolower(trim($value ?? ''));

        if ($value === '') {
            return '';
        }

        self::$transliterator ??= Transliterator::create('Any-Latin; Latin-ASCII');

        return self::$transliterator?->transliterate($value) ?: $value;
    }

    private function collapse(string $value): string
    {
        return trim(preg_replace('/\s+/', ' ', $value) ?? '');
    }

    private function blankToNull(string $value): ?string
    {
        return $value === '' ? null : $value;
    }
}
